//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPortal.Web.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoctorPortalDBEntities : DbContext
    {
        public DoctorPortalDBEntities()
            : base("name=DoctorPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HospitalContact> HospitalContacts { get; set; }
        public virtual DbSet<HospitalMaster> HospitalMasters { get; set; }
        public virtual DbSet<HospitalWorkingDay> HospitalWorkingDays { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<DepartmentImages> DepartmentImages { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<FAQQuestions> FAQQuestions { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<tblIcons> tblIcons { get; set; }
        public virtual DbSet<PatientMaster> PatientMaster { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
    }
}
